name: Salesforce Deployment

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      instance_url:
        required: true
        type: string
      username:
        required: true
        type: string
      rsa_private_key:
        required: true
        type: string
      client_id:
        required: true
        type: string

env:
  RSA_PRIVATE_KEY: ${{ inputs.RSA_PRIVATE_KEY }}
  CLIENT_ID: ${{ inputs.CLIENT_ID }}
  INSTANCE_URL: ${{ inputs.instance_url }}
  USERNAME: ${{ inputs.username }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Inputs
        run: |
          echo "Private Key: $RSA_PRIVATE_KEY"
          echo "Client ID: $CLIENT_ID"
          echo "Instance Url: $INSTANCE_URL"
          echo "Username: $USERNAME"

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf update

      - name: Save Key to File
        run: |
          echo "$RSA_PRIVATE_KEY" > private_key.crt
          echo "rsa_key=private_key.crt" >> $GITHUB_OUTPUT
        id: save_key
      
      - name: Authenticate with Salesforce Org
        env:
          RSA_KEY_FILE_NAME: ${{ steps.save_key.outputs.rsa_key }}
        run: |
          sf org login jwt --client-id "$PRODUCTION_CLIENT_ID" --jwt-key-file "$RSA_KEY_FILE_NAME" --username "$USERNAME" --alias deployment-org --instance-url "$INSTANCE_URL"

      - name: Deploy to Org
        run: sf project deploy start -o deployment-org