name: Salesforce Sandbox Deployment

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf update

      - name: Save Key to File
        run: |
          echo "${SANDBOX_KEY}" > sandbox.crt
          echo "sandbox_key=sandbox.crt" >> $GITHUB_OUTPUT
        id: save_key
        env:
          SANDBOX_KEY: ${{ secrets.SANDBOX_KEY }}
      
      - name: Authenticate with Salesforce Sandbox Org
        run: |
          sf org login jwt --client-id ${SANDBOX_CLIENT_ID} --jwt-key-file ${{ steps.save_key.outputs.sandbox_key }} --username ${SANDBOX_USERNAME} --alias sandbox-org --instance-url ${SANDBOX_INSTANCE_URL} 
        env:
          SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
          SANDBOX_USERNAME: ${{ secrets.SANDBOX_USERNAME }}
          SANDBOX_INSTANCE_URL: ${{ secrets.SANDBOX_INSTANCE_URL }}

      - name: Deploy to Sandbox
        run: sf project deploy start -o sandbox-org

