name: Salesforce Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy_base.yaml
    with:
      instance_url: ${{ secrets.PRODUCTION_INSTANCE_URL }}
      username: ${{ secrets.PRODUCTION_USERNAME }}
      rsa_private_key: ${{ secrets.PRODUCTION_KEY }}
      client_id: ${{ secrets.PRODUCTION_CLIENT_ID }}
