name: Salesforce Sandbox Deployment

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-sandbox:
    uses: ./.github/workflows/deploy_base.yaml
    with:
      instance_url: ${{ secrets.SANDBOX_INSTANCE_URL }}
      username: ${{ secrets.SANDBOX_USERNAME }}
      rsa_private_key: ${{ secrets.SANDBOX_KEY }}
      client_id: ${{ secrets.SANDBOX_CLIENT_ID }}
      

    
 

