name: Salesforce Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf update

      - name: Save Key to File
        run: |
          echo "${PRODUCTION_KEY}" > production.crt
          echo "production_key=production.crt" >> $GITHUB_OUTPUT
        id: save_key
        env:
          PRODUCTION_KEY: ${{ secrets.PRODUCTION_KEY }}
      
      - name: Authenticate with Salesforce Production Org
        run: |
          sf org login jwt --client-id ${PRODUCTION_CLIENT_ID} --jwt-key-file ${{ steps.save_key.outputs.production_key }} --username ${PRODUCTION_USERNAME} --alias production-org --instance-url ${PRODUCTION_INSTANCE_URL} 
        env:
          PRODUCTION_CLIENT_ID: ${{ secrets.PRODUCTION_CLIENT_ID }}
          PRODUCTION_USERNAME: ${{ secrets.PRODUCTION_USERNAME }}
          PRODUCTION_INSTANCE_URL: ${{ secrets.PRODUCTION_INSTANCE_URL }}

      - name: Deploy to Sandbox
        run: sf project deploy start -o production-org
